kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config
  namespace: plex
spec:
  storageClassName: kadalu.external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi