apiVersion: v1
kind: Service
metadata:
  name: plex-service
  labels:
    app: plex
spec:
  selector:
    app: plex
  ports:
  - name: plex-http
    protocol: TCP
    port: 8096
    targetPort: 8096
    nodePort: 30005
  type: NodePort