apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.6
  selector:
    app: plex
  ports:
  - name: plex-http
    protocol: TCP
    port: 32400
    targetPort: 32400
  selector:
    app: plex