apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: wg-easy
  labels:
    app: wg-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
    spec:
      restartPolicy: Always
      initContainers:
      - name: init
        image: busybox:1.32.0
        command:
        - sh
        - -c
        - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - name: wg-easy
        image: weejewel/wg-easy:7
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 51820
          protocol: UDP
          name: wg-easy-vpn
        - containerPort: 51821
          protocol: TCP
          name: wg-easy-web
        env:
        - name: WG_HOST
          value: "diplomacyofwar.com"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: wg-easy-pass
              key: password
        - name: WG_DEFAULT_DNS
          value: "10.1.10.201"
        - name: "WG_ALLOWED_IPS"
          value: "0.0.0.0/0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: wg-easy-config
          mountPath: /etc/wireguard
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
      volumes:
      - name: wg-easy-config
        persistentVolumeClaim:
          claimName: wg-easy-config