kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wg-easy-config
  namespace: wg-easy
spec:
  storageClassName: kadalu.ext-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi