apiVersion: v1
kind: Service
metadata:
  name: wg-easy-service
  labels:
    app: wg-easy
spec:
  selector:
    app: wg-easy
  ports:
  - name: wg-easy-vpn
    protocol: UDP
    port: 51820
    targetPort: 51820
    nodePort: 30001
  - name: wg-easy-web
    protocol: TCP
    port: 51821
    targetPort: 51821
    nodePort: 30002
  type: NodePort


apiVersion: v1
kind: Service
metadata:
  name: blocky-service-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "F5XFhlQjAHk49Ncsl3zwDwlZjC46pD05"
  type: LoadBalancer
  loadBalancerIP: 10.1.10.2
  ports:
    - name: blocky-dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: wg-easy