apiVersion: v1
kind: Service
metadata:
  name: wg-easy-vpn
  namespace: wg-easy
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.5
  selector:
    app: wg-easy
  ports:
  - name: wg-easy-vpn
    protocol: UDP
    port: 51820
    targetPort: 51820
  selector:
    app: wg-easy
---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.4
  ports:
  - name: wg-easy-web
    protocol: TCP
    port: 51821
    targetPort: 51821
  selector:
    app: wg-easy