kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-configinc
  namespace: mosquitto
spec:
  storageClassName: kadalu.external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi