kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data
  namespace: mosquitto
spec:
  storageClassName: kadalu.external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi