apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.9
  ports:
  - name: http
    protocol: TCP
    port: 1883
    targetPort: 1883
  selector:
    app: mosquitto