apiVersion: v1
kind: Service
metadata:
  name: blocky-service-tcp
  namespace: blocky
  annotations:
    metallb.universe.tf/allow-shared-ip: "F5XFhlQjAHk49Ncsl3zwDwlZjC46pD05"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.3
  ports:
    - name: blocky-dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    app: blocky
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-service-udp
  namespace: blocky
  annotations:
    metallb.universe.tf/allow-shared-ip: "F5XFhlQjAHk49Ncsl3zwDwlZjC46pD05"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.3
  ports:
    - name: blocky-dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: blocky