kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  storageClassName: kadalu.external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi