apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.8
  ports:
  - name: http
    protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    app: home-assistant