kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  storageClassName: kadalu.external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi