kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-config-pvc
spec:
  storageClassName: kadalu.ext-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi