apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.7
  ports:
  - name: jellyfin-http
    protocol: TCP
    port: 8096
    targetPort: 8096
  selector:
    app: jellyfin