kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zigbee2mqtt-data
  namespace: zigbee2mqtt
spec:
  storageClassName: kadalu.external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi