apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.10
  ports:
  - name: http
    protocol: TCP
    port: 10103
    targetPort: 10103
  selector:
    app: zigbee2mqtt